### ISSUE TITLE
Extract ZODBMountPoint to a separate package

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.TemporaryFolder#12]
`Products.ZODBMountPoint` is "hidden" in this package but there seems to be no necessity to do so, it could happily live in its own package.

**Comment by dwt** [comment]
Out of interest: wouldn't it make sense to move this to one of the ZODB packages? It seems that mounting sub-databases should not rely on any of the zope infrastructure.

**Comment by dataflake** [comment]
As first step I have created the Products.ZODBMountPoint package at https://github.com/zopefoundation/Products.ZODBMountPoint and published version 1.0 at https://pypi.org/project/Products.ZODBMountPoint/. I added you as second PyPI owner.

The next step is cleaning things out of Products.TemporaryFolder. Not sure yet how much work that is. It seems to have its own `mount.py` module with ZODB mounting code, not sure why.

**Comment by dataflake** [comment]
`Products.TemporaryFolder` version 6 is now published. All code that attempts to magically create ``temp_folder`` is gone and replaced by instructions how to do it manually in the README. I added a note that due to `tempstorage` using a temporary folder is unsafe with a pointer to the Zope Book sessioning chapter about alternative sessioning implementations. I also changed the Development Status classifier for PyPI to `7 - Inactive`.

**Comment by icemac** [comment]
Thank you!
